### ISSUE TITLE
总是报错 cant resolve fs

### ISSUE THREAD

**Issue by williamnie** [cnwhy/lib-qqwry#13]
项目需要npm run build:dll 才可以运行,在执行这条命令时,一直提示
Module not found: Error: Can't resolve 'fs' in '/home/hai/Documents/aminer-master/aminer2b/node_modules/lib-qqwry/lib'
重装也不管用,请问有什么解决方案么

**Comment by cnwhy** [comment]
`fs` nodejs 的内部模块，解析IP库的时候需要用到。

你的项目应该是一个浏览器项目，`lib-qqwry`不能运行在浏览器端的项目中。
