### ISSUE TITLE
再pm2启动项目,会有 too many open files的错误

### ISSUE THREAD

**Issue by tangjoin** [cnwhy/lib-qqwry#14]
(node:11672) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: EMFILE: too many open files, open '/www/wwwroot/test/node_modules/lib-qqwry/data/qqwry.dat'

**Comment by cnwhy** [comment]
@tangjoin 能把你使用`lib-qqwry`的代码贴出来吗

**Comment by cnwhy** [comment]
@tangjoin 
可能是你每次使用都重新实例化一个解析对像,导致文件标识符过多, 
我现修改了文件标识符的使用周期,应该能解决你遇到的问题.
但我不建议每次使用都实例化一次,这样使用效率较差.

**Comment by cnwhy** [comment]
估计你已经解决了 我关了
