### ISSUE TITLE
建议命令行版本独立一个新模块

### ISSUE THREAD

**Issue by 52cik** [cnwhy/lib-qqwry#16]
模块非常好，但为什么要吧命令行硬加进来？  
单独提取一个命令行版本会好点。
保持模块小而干净，会更加优秀。

**Comment by cnwhy** [comment]
谢谢你的建议，但我还是觉得放起比较方便.

**Comment by 52cik** [comment]
我昨晚写了个 [qqwry-lite](https://github.com/52cik/qqwry-lite)，已经标明是抄袭你的模块了。:satisfied:

**Comment by cnwhy** [comment]
其实可以用v1.1.0那个版本, 只依赖一个解码gb2312的库, 
V1.2.0 版本的 流API 有个bug.
