### ISSUE TITLE
ISP信息

### ISSUE THREAD

**Issue by alphawq** [cnwhy/lib-qqwry#19]
**请问可以解析出ISP相关的信息吗？**

**Comment by cnwhy** [comment]
纯真的库没有用来专门记录ISP的字段, 只有一些IP会标识 电信,联通什么的

**Comment by alphawq** [comment]
> 纯真的库没有用来专门记录ISP的字段, 只有一些IP会标识 电信,联通什么的

好的。感谢解答。

还有几个问题：
- 如何更新纯真库？
- 在使用searchIP查询过程中（频繁调用）发现CPU负载很高，是否可以优化？

**Comment by cnwhy** [comment]
> 如何更新纯真库？

项目内可以用 `npx qqwry update` 命令更新IP库
全局安装的可以用 `qqwry update`

> 在使用searchIP查询过程中（频繁调用）发现CPU负载很高，是否可以优化？

查询过程是一个CPU密集型操作. 查询效率高,CPU负载就高

**Comment by SukkaW** [comment]
> **请问可以解析出ISP相关的信息吗？**

请参考基于 QQWry 添加更多字段的库： https://github.com/metowolf/qqwry.ipdb
