### ISSUE TITLE
朋友，IPv6的问题

### ISSUE THREAD

**Issue by jddy** [cnwhy/lib-qqwry#6]
貌似node v0.12.7 发现 有IPv6格式的IP，不知道有没有打算兼容和支持下。

另外国外的ip地址库 怎么处理，一个gbk.js 能显示完么

**Comment by cnwhy** [comment]
现在基本上没有 IPv6 格式的IP库, 兼容也没有用  
gbk.js 是用来个换字符的, IP库用的是纯真的.

**Comment by jddy** [comment]
昨天调用的时候 发现代码取出来的IP地址变成兼容IPv6的样子
::ffffff:127.0.0.1
传到qqwry里 发现出问题，没辙，只好自己转换

**Comment by cnwhy** [comment]
这个lib暂时就只是单纯的处理IPv4的东西,你有兴趣的话可以fork一下,把你的这种情况加进来.
